# HS4002 Week 8

## Practising with Count Models

Research question: **what factors influence the number of children someone has?**

We'll compare three model types for count outcomes:
1. OLS (baseline)
2. Poisson regression
3. Negative Binomial regression

Plus: overdispersion testing and marginal effects.

In [1]:
# !pip install pandas numpy plotnine statsmodels stargazer marginaleffects scipy

import pandas as pd
import numpy as np
from plotnine import *
import warnings
warnings.filterwarnings('ignore')
import statsmodels.formula.api as smf
from scipy.stats import chi2

In [2]:
raw_df = pd.read_csv("gss2022_mini2.csv")

chosen_variables = [
	'id', 'age', 'happy', 'yrlvmus', 'yrartxbt', 'yrmovie', 'yrcreat',
	'income16', 'prestg10', 'degree', 'race', 'sex', 'wrkstat', 'biokids', 'educ'
]
df = raw_df[chosen_variables].dropna().copy()

income_map = {
	1: 500,    2: 2000,   3: 3500,   4: 4500,   5: 5500,   6: 6500,
	7: 7500,   8: 9000,   9: 11250,  10: 13750, 11: 16250, 12: 18750,
	13: 21250, 14: 23750, 15: 27500, 16: 32500, 17: 37500, 18: 45000,
	19: 55000, 20: 67500, 21: 82500, 22: 100000, 23: 120000, 24: 140000,
	25: 160000, 26: 250000
}
df['income_cont']   = df['income16'].map(income_map)
df['income_10k']   = df['income_cont'] / 10000
df['age']       = raw_df.loc[df.index, 'age'] - 18

df['binary_lvmus']  = (df['yrlvmus']  == 1).astype(int)
df['binary_artxbt'] = (df['yrartxbt'] == 1).astype(int)
df['binary_movie']  = (df['yrmovie']  == 1).astype(int)
df['binary_creat']  = (df['yrcreat']  == 1).astype(int)
df['omni'] = df[['binary_lvmus','binary_artxbt','binary_movie','binary_creat']].sum(axis=1)

df['race_bin']   = pd.Categorical(df['race'].astype(str))
df['race_cat']   = df['race'].map({1: 'White', 2: 'Black'}).fillna('Other')
df['ba_binary']  = (df['degree'] >= 3).astype(int)
df['sex_woman']  = pd.Categorical(
    np.where(df['sex'] == 2, 'Woman', 'Not Woman'),
    categories=['Not Woman', 'Woman']
)
df['working']    = np.where(df['wrkstat'] <= 3, 'Working', 'Not Working')
df['happy_bin']  = (df['happy'] <= 2).astype(int)
df['happy_cat']  = np.where(df['happy'] <= 2, 'Happy', 'Not Happy')

# Starting with an OLS model

Regress no. of children (`biokids`) against income in ten thousands (`income_10k`). Note: one unit = $10,000. Name this `ols_lm1`.

In [3]:
ols_lm1 = smf.ols('biokids ~ income_10k', data=df).fit()
print(ols_lm1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                biokids   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                   0.04228
Date:                Wed, 07 Oct 2026   Prob (F-statistic):              0.837
Time:                        14:15:37   Log-Likelihood:                -1050.5
No. Observations:                 557   AIC:                             2105.
Df Residuals:                     555   BIC:                             2114.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.5647      0.107     14.639      0.000       1.355       1.775
income_10k     0.0020      0.010      0.206      0.837      -0.017       0.021
==============================================================================
Omnibus:                      147.242   Durbin-Watson:                   1.830
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              411.395
Skew:                           1.287   Prob(JB):                     4.64e-90
Kurtosis:                       6.332   Cond. No.                         17.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

How would you interpret the coefficient for `income_10k`? What is unusual about using OLS on a count variable?

# Continuing with a Poisson Model

Use `smf.poisson()` — equivalent to `glm(..., family='poisson')` in R.

In [4]:
po_lm1 = smf.poisson('biokids ~ income_10k', data=df).fit()
print(po_lm1.summary())

Optimization terminated successfully.
         Current function value: 1.767601
         Iterations 3
                          Poisson Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:                        Poisson   Df Residuals:                      555
Method:                           MLE   Df Model:                            1
Date:                Wed, 07 Oct 2026   Pseudo R-squ.:               3.454e-05
Time:                        14:16:01   Log-Likelihood:                -984.55
converged:                       True   LL-Null:                       -984.59
Covariance Type:            nonrobust   LLR p-value:                    0.7942
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4478      0.053      8.410      0.000       0.343       0.552
income_10k     0.0012      0.005      0.261      0.794      -0.008       0.011
==============================================================================

In [5]:
# Interpretation of income_10k. 
# The coefficient of income_10k is 0.0012, therefore: a one unit change in income_10k is expected to change the number of children by a factor of exp(0.0012), ceteris paribus
# Alternatively, it can be a percentage change of : 100 x [exp(0.0012)-1]%

Interpret the coefficient on `income_10k`. Do not read it as you would an OLS coefficient.

Poisson coefficients are **factors of change**: a one-unit change in `income_10k` is expected to change the number of children by a factor of exp(β), ceteris paribus.

You can alternatively read this as a **percentage change**: 100 × [exp(β) − 1]%.

In [6]:
import numpy as np
b = po_lm1.params['income_10k']
print(f'Factor of change, exp(b): {np.exp(b):.4f}')
print(f'Percentage change, 100 * [exp(b) - 1]: {100 * (np.exp(b) - 1):.2f}%')

Factor of change, exp(b): 1.0012
Percentage change, 100 * [exp(b) - 1]: 0.12%

# Adding Age

Add `age` to both models. `age` is centered at 18, so 0 is an 18-year-old. Save as `ols_lm2` and `po_lm2`.

In [8]:
ols_lm2 = smf.ols('biokids ~ income_10k + age', data=df).fit()
po_lm2  = smf.poisson('biokids ~ income_10k + age', data=df).fit()
print(po_lm2.summary())

Optimization terminated successfully.
         Current function value: 1.720780
         Iterations 5
                          Poisson Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:                        Poisson   Df Residuals:                      554
Method:                           MLE   Df Model:                            2
Date:                Wed, 07 Oct 2026   Pseudo R-squ.:                 0.02652
Time:                        14:25:27   Log-Likelihood:                -958.47
converged:                       True   LL-Null:                       -984.59
Covariance Type:            nonrobust   LLR p-value:                 4.563e-12
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0674      0.094     -0.720      0.472      -0.251       0.116
income_10k     0.0008      0.005      0.165      0.869      -0.009       0.010
age            0.0143      0.002      7.151      0.000       0.010       0.018
==============================================================================

## Comparing the Poisson Models via Likelihood Ratio Test

In [9]:
lr_stat = 2 * (po_lm2.llf - po_lm1.llf)
df_diff = po_lm2.df_model - po_lm1.df_model
p_val   = chi2.sf(lr_stat, df_diff)
print(f'LR statistic = {lr_stat:.4f}, df = {df_diff:.0f}, p-value = {p_val:.6f}')

LR statistic = 52.1579, df = 1, p-value = 0.000000

In [10]:
# A likelihood ratio test indicated that adding age significantly improved the fit of the Poisson regression model, LR(1) = 52.16, p< 0.001, this suggests
# Suggests that the model including age fits the data substantially better than the model containing income alone

# Building a Negative Binomial Model

Negative binomial relaxes the Poisson assumption that variance = mean (allowing overdispersion).

Equivalent to R's `MASS::glm.nb()`.

Read the coefficients the same way as in a Poisson model: as a factor of change, exp(β), or as a percentage change, 100 × [exp(β) − 1]%.

In [11]:
nb_m1 = smf.negativebinomial('biokids ~ income_10k + age', data=df).fit()
print(nb_m1.summary())

Optimization terminated successfully.
         Current function value: 1.670251
         Iterations: 14
         Function evaluations: 19
         Gradient evaluations: 19
                     NegativeBinomial Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:               NegativeBinomial   Df Residuals:                      554
Method:                           MLE   Df Model:                            2
Date:                Wed, 07 Oct 2026   Pseudo R-squ.:                 0.01718
Time:                        14:31:16   Log-Likelihood:                -930.33
converged:                       True   LL-Null:                       -946.59
Covariance Type:            nonrobust   LLR p-value:                 8.681e-08
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0832      0.116     -0.718      0.473      -0.310       0.144
income_10k     0.0005      0.006      0.081      0.936      -0.011       0.012
age            0.0148      0.003      5.755      0.000       0.010       0.020
alpha          0.3822      0.073      5.212      0.000       0.239       0.526
==============================================================================

In [12]:
from stargazer.stargazer import Stargazer

sg = Stargazer([ols_lm2, po_lm2, nb_m1])
sg.title('Number of Children')
sg.custom_columns(['OLS', 'Poisson', 'Neg. Binomial'], [1, 1, 1])

# Ending the cell on the object itself renders the table in the notebook
sg

## Test for Overdispersion

Was NB necessary? We test whether the NB's dispersion parameter (alpha) is significantly different from 0. If alpha = 0, the NB reduces to Poisson.

This is equivalent to R's `pscl::odTest()`.

In [13]:
# Overdispersion test: LR comparing NB vs Poisson
# Under H0 (Poisson), the test statistic has a chi-square(1)/2 distribution
# because the null is on the boundary of the parameter space
lr_od = 2 * (nb_m1.llf - po_lm2.llf)
p_od  = 0.5 * chi2.sf(lr_od, 1)
print(f'Overdispersion LR statistic = {lr_od:.4f}')
print(f'p-value (one-sided) = {p_od:.6f}')
print('NB preferred over Poisson:', p_od < 0.05)

Overdispersion LR statistic = 56.2895
p-value (one-sided) = 0.000000
NB preferred over Poisson: True

# Marginal Effects

A marginal effect is the expected change in the number of children when an independent variable increases by one unit, ceteris paribus. Compute them the same way as for the logit models.

In [14]:
from marginaleffects import avg_comparisons, comparisons

## Average marginal effects of income

In [15]:
avg_comparisons(po_lm2, variables='income_10k')

shape: (1, 7)
┌──────────┬───────────┬───────┬─────────┬───────┬─────────┬───────┐
│ Estimate ┆ Std.Error ┆ z     ┆ P(>|z|) ┆ S     ┆ 2.5%    ┆ 97.5% │
│ ---      ┆ ---       ┆ ---   ┆ ---     ┆ ---   ┆ ---     ┆ ---   │
│ str      ┆ str       ┆ str   ┆ str     ┆ str   ┆ str     ┆ str   │
╞══════════╪═══════════╪═══════╪═════════╪═══════╪═════════╪═══════╡
│ 0.00124  ┆ 0.0075    ┆ 0.165 ┆ 0.869   ┆ 0.203 ┆ -0.0135 ┆ 0.016 │
└──────────┴───────────┴───────┴─────────┴───────┴─────────┴───────┘
Term: income_10k
Contrast: +1

In [16]:
avg_comparisons(nb_m1, variables='income_10k')

shape: (1, 7)
┌──────────┬───────────┬────────┬─────────┬───────┬────────┬────────┐
│ Estimate ┆ Std.Error ┆ z      ┆ P(>|z|) ┆ S     ┆ 2.5%   ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---    ┆ ---     ┆ ---   ┆ ---    ┆ ---    │
│ str      ┆ str       ┆ str    ┆ str     ┆ str   ┆ str    ┆ str    │
╞══════════╪═══════════╪════════╪═════════╪═══════╪════════╪════════╡
│ 0.00077  ┆ 0.00953   ┆ 0.0808 ┆ 0.936   ┆ 0.096 ┆ -0.018 ┆ 0.0195 │
└──────────┴───────────┴────────┴─────────┴───────┴────────┴────────┘
Term: income_10k
Contrast: +1

## Marginal effect at the mean of income

In [17]:
comparisons(po_lm2, variables='income_10k', newdata='mean')

shape: (1, 7)
┌──────────┬───────────┬───────┬─────────┬───────┬─────────┬────────┐
│ Estimate ┆ Std.Error ┆ z     ┆ P(>|z|) ┆ S     ┆ 2.5%    ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---   ┆ ---     ┆ ---   ┆ ---     ┆ ---    │
│ str      ┆ str       ┆ str   ┆ str     ┆ str   ┆ str     ┆ str    │
╞══════════╪═══════════╪═══════╪═════════╪═══════╪═════════╪════════╡
│ 0.0012   ┆ 0.00727   ┆ 0.165 ┆ 0.869   ┆ 0.203 ┆ -0.0131 ┆ 0.0155 │
└──────────┴───────────┴───────┴─────────┴───────┴─────────┴────────┘
Term: income_10k
Contrast: +1

In [18]:
comparisons(nb_m1, variables='income_10k', newdata='mean')

shape: (1, 7)
┌──────────┬───────────┬────────┬─────────┬───────┬─────────┬────────┐
│ Estimate ┆ Std.Error ┆ z      ┆ P(>|z|) ┆ S     ┆ 2.5%    ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---    ┆ ---     ┆ ---   ┆ ---     ┆ ---    │
│ str      ┆ str       ┆ str    ┆ str     ┆ str   ┆ str     ┆ str    │
╞══════════╪═══════════╪════════╪═════════╪═══════╪═════════╪════════╡
│ 0.000746 ┆ 0.00923   ┆ 0.0808 ┆ 0.936   ┆ 0.096 ┆ -0.0174 ┆ 0.0189 │
└──────────┴───────────┴────────┴─────────┴───────┴─────────┴────────┘
Term: income_10k
Contrast: +1

# Independent Investigation: Education and Number of Children

Investigate the relationship between **no. of children** (`biokids`) and **BA education** (`ba_binary`).

Do the following:

1. Include these independent variables: `ba_binary`, `age`, `income_10k`, `sex_woman`, and `race_bin`.
2. Build OLS, Poisson, and Negative Binomial models.
3. Produce a Stargazer table comparing the three models.
4. Compute marginal effects for each model.
5. Decide which model is best. Justify.
6. Answer: does a person with a BA have more or fewer children, and by how much? For the Poisson and negative binomial models, report a factor of change or a percentage change.

Poisson Regression Results, OLS, Negative Binom

In [21]:
ols_lm3 = smf.ols('biokids ~ income_10k + age + ba_binary + sex_woman + race_bin', data=df).fit()
po_lm3  = smf.poisson('biokids ~ income_10k + age + ba_binary + sex_woman + race_bin', data=df).fit()
print(po_lm3.summary())
print(ols_lm3.summary())

Optimization terminated successfully.
         Current function value: 1.671346
         Iterations 5
                          Poisson Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:                        Poisson   Df Residuals:                      550
Method:                           MLE   Df Model:                            6
Date:                Wed, 07 Oct 2026   Pseudo R-squ.:                 0.05449
Time:                        15:23:35   Log-Likelihood:                -930.94
converged:                       True   LL-Null:                       -984.59
Covariance Type:            nonrobust   LLR p-value:                 7.505e-21
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             -0.3234      0.112     -2.885      0.004      -0.543      -0.104
sex_woman[T.Woman]     0.3184      0.070      4.564      0.000       0.182       0.455
race_bin[T.2.0]        0.3711      0.094      3.955      0.000       0.187       0.555
race_bin[T.3.0]        0.0390      0.157      0.249      0.803      -0.268       0.346
income_10k             0.0142      0.005      2.749      0.006       0.004       0.024
age                    0.0154      0.002      7.507      0.000       0.011       0.019
ba_binary             -0.3114      0.075     -4.136      0.000      -0.459      -0.164
======================================================================================
                            OLS Regression Results
==============================================================================
Dep. Variable:                biokids   R-squared:                       0.118
Model:                            OLS   Adj. R-squared:                  0.109
Method:                 Least Squares   F-statistic:                     12.29
Date:                Wed, 07 Oct 2026   Prob (F-statistic):           5.36e-13
Time:                        15:23:35   Log-Likelihood:                -1015.5
No. Observations:                 557   AIC:                             2045.
Df Residuals:                     550   BIC:                             2075.
Df Model:                           6
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              0.4837      0.190      2.547      0.011       0.111       0.857
sex_woman[T.Woman]     0.4935      0.130      3.798      0.000       0.238       0.749
race_bin[T.2.0]        0.6263      0.201      3.117      0.002       0.232       1.021
race_bin[T.3.0]        0.0643      0.282      0.228      0.820      -0.489       0.618
income_10k             0.0216      0.010      2.165      0.031       0.002       0.041
age                    0.0233      0.004      6.202      0.000       0.016       0.031
ba_binary             -0.4814      0.141     -3.410      0.001      -0.759      -0.204
==============================================================================
Omnibus:                      156.400   Durbin-Watson:                   1.934
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              482.642
Skew:                           1.327   Prob(JB):                    1.57e-105
Kurtosis:                       6.709   Cond. No.                         175.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [20]:
nb_m2 = smf.negativebinomial('biokids ~ income_10k + age +  ba_binary + sex_woman + race_bin', data=df).fit()
print(nb_m2.summary())

Optimization terminated successfully.
         Current function value: 1.637030
         Iterations: 28
         Function evaluations: 34
         Gradient evaluations: 34
                     NegativeBinomial Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:               NegativeBinomial   Df Residuals:                      550
Method:                           MLE   Df Model:                            6
Date:                Wed, 07 Oct 2026   Pseudo R-squ.:                 0.03673
Time:                        15:22:54   Log-Likelihood:                -911.83
converged:                       True   LL-Null:                       -946.59
Covariance Type:            nonrobust   LLR p-value:                 5.111e-13
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             -0.3463      0.134     -2.591      0.010      -0.608      -0.084
sex_woman[T.Woman]     0.3242      0.085      3.808      0.000       0.157       0.491
race_bin[T.2.0]        0.3756      0.119      3.143      0.002       0.141       0.610
race_bin[T.3.0]        0.0414      0.189      0.219      0.827      -0.330       0.413
income_10k             0.0149      0.006      2.322      0.020       0.002       0.028
age                    0.0160      0.003      6.348      0.000       0.011       0.021
ba_binary             -0.3301      0.093     -3.551      0.000      -0.512      -0.148
alpha                  0.2962      0.066      4.486      0.000       0.167       0.426
======================================================================================

Stargazer table

In [22]:
from stargazer.stargazer import Stargazer

sg = Stargazer([ols_lm3, po_lm3, nb_m2])
sg.title('Number of Children')
sg.custom_columns(['OLS', 'Poisson', 'Neg. Binomial'], [1, 1, 1])

# Ending the cell on the object itself renders the table in the notebook
sg

In [23]:
avg_comparisons(po_lm3)

shape: (6, 9)
┌────────────┬───────────────────┬──────────┬───────────┬───┬──────────┬──────┬─────────┬────────┐
│ Term       ┆ Contrast          ┆ Estimate ┆ Std.Error ┆ … ┆ P(>|z|)  ┆ S    ┆ 2.5%    ┆ 97.5%  │
│ ---        ┆ ---               ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---  ┆ ---     ┆ ---    │
│ str        ┆ str               ┆ str      ┆ str       ┆   ┆ str      ┆ str  ┆ str     ┆ str    │
╞════════════╪═══════════════════╪══════════╪═══════════╪═══╪══════════╪══════╪═════════╪════════╡
│ age        ┆ +1                ┆ 0.0244   ┆ 0.00335   ┆ … ┆ 1.18e-12 ┆ 39.6 ┆ 0.0178  ┆ 0.031  │
│ ba_binary  ┆ 1 - 0             ┆ -0.486   ┆ 0.117     ┆ … ┆ 3.55e-05 ┆ 14.8 ┆ -0.715  ┆ -0.257 │
│ income_10k ┆ +1                ┆ 0.0224   ┆ 0.00819   ┆ … ┆ 0.00639  ┆ 7.29 ┆ 0.00634 ┆ 0.0385 │
│ race_bin   ┆ 2.0 - 1.0         ┆ 0.673    ┆ 0.194     ┆ … ┆ 0.000575 ┆ 10.8 ┆ 0.291   ┆ 1.06   │
│ race_bin   ┆ 3.0 - 1.0         ┆ 0.0596   ┆ 0.244     ┆ … ┆ 0.807    ┆ 0.31 ┆ -0.419  ┆ 0.538  │
│ sex_woman  ┆ Woman - Not Woman ┆ 0.496    ┆ 0.107     ┆ … ┆ 4.92e-06 ┆ 17.6 ┆ 0.285   ┆ 0.707  │
└────────────┴───────────────────┴──────────┴───────────┴───┴──────────┴──────┴─────────┴────────┘

In [24]:
avg_comparisons(ols_lm3)

shape: (6, 9)
┌────────────┬───────────────────┬──────────┬───────────┬───┬──────────┬───────┬─────────┬────────┐
│ Term       ┆ Contrast          ┆ Estimate ┆ Std.Error ┆ … ┆ P(>|z|)  ┆ S     ┆ 2.5%    ┆ 97.5%  │
│ ---        ┆ ---               ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---   ┆ ---     ┆ ---    │
│ str        ┆ str               ┆ str      ┆ str       ┆   ┆ str      ┆ str   ┆ str     ┆ str    │
╞════════════╪═══════════════════╪══════════╪═══════════╪═══╪══════════╪═══════╪═════════╪════════╡
│ age        ┆ +1                ┆ 0.0233   ┆ 0.00376   ┆ … ┆ 1.1e-09  ┆ 29.8  ┆ 0.0159  ┆ 0.0307 │
│ ba_binary  ┆ 1 - 0             ┆ -0.481   ┆ 0.141     ┆ … ┆ 0.000698 ┆ 10.5  ┆ -0.759  ┆ -0.204 │
│ income_10k ┆ +1                ┆ 0.0216   ┆ 0.00999   ┆ … ┆ 0.0308   ┆ 5.02  ┆ 0.00201 ┆ 0.0413 │
│ race_bin   ┆ 2.0 - 1.0         ┆ 0.626    ┆ 0.201     ┆ … ┆ 0.00192  ┆ 9.02  ┆ 0.232   ┆ 1.02   │
│ race_bin   ┆ 3.0 - 1.0         ┆ 0.0643   ┆ 0.282     ┆ … ┆ 0.82     ┆ 0.287 ┆ -0.489  ┆ 0.618  │
│ sex_woman  ┆ Woman - Not Woman ┆ 0.494    ┆ 0.13      ┆ … ┆ 0.000162 ┆ 12.6  ┆ 0.238   ┆ 0.749  │
└────────────┴───────────────────┴──────────┴───────────┴───┴──────────┴───────┴─────────┴────────┘

In [25]:
avg_comparisons(nb_m2)

shape: (6, 9)
┌────────────┬───────────────────┬──────────┬───────────┬───┬──────────┬───────┬─────────┬────────┐
│ Term       ┆ Contrast          ┆ Estimate ┆ Std.Error ┆ … ┆ P(>|z|)  ┆ S     ┆ 2.5%    ┆ 97.5%  │
│ ---        ┆ ---               ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---   ┆ ---     ┆ ---    │
│ str        ┆ str               ┆ str      ┆ str       ┆   ┆ str      ┆ str   ┆ str     ┆ str    │
╞════════════╪═══════════════════╪══════════╪═══════════╪═══╪══════════╪═══════╪═════════╪════════╡
│ age        ┆ +1                ┆ 0.0254   ┆ 0.00422   ┆ … ┆ 3.54e-09 ┆ 28.1  ┆ 0.0171  ┆ 0.0337 │
│ ba_binary  ┆ 1 - 0             ┆ -0.515   ┆ 0.145     ┆ … ┆ 0.000419 ┆ 11.2  ┆ -0.801  ┆ -0.23  │
│ income_10k ┆ +1                ┆ 0.0237   ┆ 0.0103    ┆ … ┆ 0.0217   ┆ 5.53  ┆ 0.00348 ┆ 0.0439 │
│ race_bin   ┆ 2.0 - 1.0         ┆ 0.684    ┆ 0.25      ┆ … ┆ 0.00644  ┆ 7.28  ┆ 0.193   ┆ 1.18   │
│ race_bin   ┆ 3.0 - 1.0         ┆ 0.0634   ┆ 0.295     ┆ … ┆ 0.83     ┆ 0.269 ┆ -0.517  ┆ 0.644  │
│ sex_woman  ┆ Woman - Not Woman ┆ 0.506    ┆ 0.133     ┆ … ┆ 0.000151 ┆ 12.7  ┆ 0.245   ┆ 0.766  │
└────────────┴───────────────────┴──────────┴───────────┴───┴──────────┴───────┴─────────┴────────┘

Having a BA is associated with about 0.48 to 0.52 fewer children on average. All three models agree, and all are significant (p < 0.001).

In [27]:
# If NB was necessary 

lr_od = 2 * (nb_m2.llf - po_lm3.llf)
p_od  = 0.5 * chi2.sf(lr_od, 1)
print(f'Overdispersion LR statistic = {lr_od:.4f}')
print(f'p-value (one-sided) = {p_od:.6f}')
print('NB preferred over Poisson:', p_od < 0.05)

Overdispersion LR statistic = 38.2281
p-value (one-sided) = 0.000000
NB preferred over Poisson: True

Comparing AIC, BIC

In [30]:
for name, m in [('OLS', ols_lm3), ('Poisson', po_lm3), ('NB', nb_m2)]:
    print(f'{name}: AIC = {m.aic:.1f}, BIC = {m.bic:.1f}')

OLS: AIC = 2044.9, BIC = 2075.2
Poisson: AIC = 1875.9, BIC = 1906.1
NB: AIC = 1839.7, BIC = 1874.2

From the above 3 models, 
 NB is the best model: the overdispersion test is significant (p < 0.001), and it has the lowest AIC (1839.7) and BIC (1874.2).
# Poisson assumes variance = mean, so its standard errors are too small; NB corrects this.
# OLS is unsuitable for counts: it can predict negative values and assumes constant variance.

A person with a BA is expected to have fewer children, holding age, income, sex and race constant. In the negative binomial model, which is the best model, having a BA changes the expected number of children by a factor of 0.72, about 28% fewer. The Poisson model gives a similar result, a factor of 0.73 or about 27% fewer. In absolute terms, that is about half a child fewer on average (marginal effects of −0.48 for OLS, −0.49 for Poisson and −0.52 for NB). The effect is statistically significant in all three models (p < 0.001).