# HS4002 Week 8

## Practising with Count Models

Research question: **what factors influence the number of children someone has?**

We'll compare three model types for count outcomes:
1. OLS (baseline)
2. Poisson regression
3. Negative Binomial regression

Plus: overdispersion testing and marginal effects.

In [1]:
# !pip install pandas numpy plotnine statsmodels stargazer marginaleffects scipy

import pandas as pd
import numpy as np
from plotnine import *
import warnings
warnings.filterwarnings('ignore')
import statsmodels.formula.api as smf
from scipy.stats import chi2

In [2]:
raw_df = pd.read_csv("gss2022_mini2.csv")

chosen_variables = [
	'id', 'age', 'happy', 'yrlvmus', 'yrartxbt', 'yrmovie', 'yrcreat',
	'income16', 'prestg10', 'degree', 'race', 'sex', 'wrkstat', 'biokids', 'educ'
]
df = raw_df[chosen_variables].dropna().copy()

income_map = {
	1: 500,    2: 2000,   3: 3500,   4: 4500,   5: 5500,   6: 6500,
	7: 7500,   8: 9000,   9: 11250,  10: 13750, 11: 16250, 12: 18750,
	13: 21250, 14: 23750, 15: 27500, 16: 32500, 17: 37500, 18: 45000,
	19: 55000, 20: 67500, 21: 82500, 22: 100000, 23: 120000, 24: 140000,
	25: 160000, 26: 250000
}
df['income_cont']   = df['income16'].map(income_map)
df['income_10k']   = df['income_cont'] / 10000
df['age']       = raw_df.loc[df.index, 'age'] - 18

df['binary_lvmus']  = (df['yrlvmus']  == 1).astype(int)
df['binary_artxbt'] = (df['yrartxbt'] == 1).astype(int)
df['binary_movie']  = (df['yrmovie']  == 1).astype(int)
df['binary_creat']  = (df['yrcreat']  == 1).astype(int)
df['omni'] = df[['binary_lvmus','binary_artxbt','binary_movie','binary_creat']].sum(axis=1)

df['race_bin']   = pd.Categorical(df['race'].astype(str))
df['race_cat']   = df['race'].map({1: 'White', 2: 'Black'}).fillna('Other')
df['ba_binary']  = (df['degree'] >= 3).astype(int)
df['sex_woman']  = pd.Categorical(
    np.where(df['sex'] == 2, 'Woman', 'Not Woman'),
    categories=['Not Woman', 'Woman']
)
df['working']    = np.where(df['wrkstat'] <= 3, 'Working', 'Not Working')
df['happy_bin']  = (df['happy'] <= 2).astype(int)
df['happy_cat']  = np.where(df['happy'] <= 2, 'Happy', 'Not Happy')

# Starting with an OLS model

Regress no. of children (`biokids`) against income in ten thousands (`income_10k`). Note: one unit = $10,000. Name this `ols_lm1`.

In [3]:
ols_lm1 = smf.ols('biokids ~ income_10k', data=df).fit()
print(ols_lm1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                biokids   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                   0.04228
Date:                Tue, 13 Oct 2026   Prob (F-statistic):              0.837
Time:                        12:46:16   Log-Likelihood:                -1050.5
No. Observations:                 557   AIC:                             2105.
Df Residuals:                     555   BIC:                             2114.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.5647      0.107     14.639      0.000       1.355       1.775
income_10k     0.0020      0.010      0.206      0.837      -0.017       0.021
==============================================================================
Omnibus:                      147.242   Durbin-Watson:                   1.830
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              411.395
Skew:                           1.287   Prob(JB):                     4.64e-90
Kurtosis:                       6.332   Cond. No.                         17.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

How would you interpret the coefficient for `income_10k`? What is unusual about using OLS on a count variable?

The coefficient suggests that for every $10000 increase in income level, the number of children a person has is estimated to increase by 0.002. While this can explain changes in the average number of children for a group, it is not possible for an individual to have 0.002 more children. Furthermore, there is the possibility of the OLS model predicting negative outcomes.

# Continuing with a Poisson Model

Use `smf.poisson()` — equivalent to `glm(..., family='poisson')` in R.

In [4]:
po_lm1 = smf.poisson('biokids ~ income_10k', data=df).fit()
print(po_lm1.summary())

Optimization terminated successfully.
         Current function value: 1.767601
         Iterations 3
                          Poisson Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:                        Poisson   Df Residuals:                      555
Method:                           MLE   Df Model:                            1
Date:                Tue, 13 Oct 2026   Pseudo R-squ.:               3.454e-05
Time:                        12:56:47   Log-Likelihood:                -984.55
converged:                       True   LL-Null:                       -984.59
Covariance Type:            nonrobust   LLR p-value:                    0.7942
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4478      0.053      8.410      0.000       0.343       0.552
income_10k     0.0012      0.005      0.261      0.794      -0.008       0.011
==============================================================================

Interpret the coefficient on `income_10k`. Do not read it as you would an OLS coefficient.

Poisson coefficients are **factors of change**: a one-unit change in `income_10k` is expected to change the number of children by a factor of exp(β), ceteris paribus.

You can alternatively read this as a **percentage change**: 100 × [exp(β) − 1]%.

For every $10000 increase in income level, the expected number of children is estimated to increase by 0.0012 log counts. However, this is not a statistically significant outcome as the p-value is greater than 0.05. This suggests that an increase in income does not predict changes in number of children.

In [5]:
import numpy as np
b = po_lm1.params['income_10k']
print(f'Factor of change, exp(b): {np.exp(b):.4f}')
print(f'Percentage change, 100 * [exp(b) - 1]: {100 * (np.exp(b) - 1):.2f}%')

Factor of change, exp(b): 1.0012
Percentage change, 100 * [exp(b) - 1]: 0.12%

# Adding Age

Add `age` to both models. `age` is centered at 18, so 0 is an 18-year-old. Save as `ols_lm2` and `po_lm2`.

In [6]:
ols_lm2 = smf.ols('biokids ~ income_10k + age', data=df).fit()
po_lm2  = smf.poisson('biokids ~ income_10k + age', data=df).fit()
print(po_lm2.summary())

Optimization terminated successfully.
         Current function value: 1.720780
         Iterations 5
                          Poisson Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:                        Poisson   Df Residuals:                      554
Method:                           MLE   Df Model:                            2
Date:                Tue, 13 Oct 2026   Pseudo R-squ.:                 0.02652
Time:                        13:03:24   Log-Likelihood:                -958.47
converged:                       True   LL-Null:                       -984.59
Covariance Type:            nonrobust   LLR p-value:                 4.563e-12
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0674      0.094     -0.720      0.472      -0.251       0.116
income_10k     0.0008      0.005      0.165      0.869      -0.009       0.010
age            0.0143      0.002      7.151      0.000       0.010       0.018
==============================================================================

## Comparing the Poisson Models via Likelihood Ratio Test

In [7]:
lr_stat = 2 * (po_lm2.llf - po_lm1.llf)
df_diff = po_lm2.df_model - po_lm1.df_model
p_val   = chi2.sf(lr_stat, df_diff)
print(f'LR statistic = {lr_stat:.4f}, df = {df_diff:.0f}, p-value = {p_val:.6f}')

LR statistic = 52.1579, df = 1, p-value = 0.000000

# Building a Negative Binomial Model

Negative binomial relaxes the Poisson assumption that variance = mean (allowing overdispersion).

Equivalent to R's `MASS::glm.nb()`.

Read the coefficients the same way as in a Poisson model: as a factor of change, exp(β), or as a percentage change, 100 × [exp(β) − 1]%.

In [8]:
nb_m1 = smf.negativebinomial('biokids ~ income_10k + age', data=df).fit()
print(nb_m1.summary())

Optimization terminated successfully.
         Current function value: 1.670251
         Iterations: 14
         Function evaluations: 19
         Gradient evaluations: 19
                     NegativeBinomial Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:               NegativeBinomial   Df Residuals:                      554
Method:                           MLE   Df Model:                            2
Date:                Tue, 13 Oct 2026   Pseudo R-squ.:                 0.01718
Time:                        13:04:18   Log-Likelihood:                -930.33
converged:                       True   LL-Null:                       -946.59
Covariance Type:            nonrobust   LLR p-value:                 8.681e-08
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0832      0.116     -0.718      0.473      -0.310       0.144
income_10k     0.0005      0.006      0.081      0.936      -0.011       0.012
age            0.0148      0.003      5.755      0.000       0.010       0.020
alpha          0.3822      0.073      5.212      0.000       0.239       0.526
==============================================================================

In [9]:
from stargazer.stargazer import Stargazer

sg = Stargazer([ols_lm2, po_lm2, nb_m1])
sg.title('Number of Children')
sg.custom_columns(['OLS', 'Poisson', 'Neg. Binomial'], [1, 1, 1])

# Ending the cell on the object itself renders the table in the notebook
sg

## Test for Overdispersion

Was NB necessary? We test whether the NB's dispersion parameter (alpha) is significantly different from 0. If alpha = 0, the NB reduces to Poisson.

This is equivalent to R's `pscl::odTest()`.

In [10]:
# Overdispersion test: LR comparing NB vs Poisson
# Under H0 (Poisson), the test statistic has a chi-square(1)/2 distribution
# because the null is on the boundary of the parameter space
lr_od = 2 * (nb_m1.llf - po_lm2.llf)
p_od  = 0.5 * chi2.sf(lr_od, 1)
print(f'Overdispersion LR statistic = {lr_od:.4f}')
print(f'p-value (one-sided) = {p_od:.6f}')
print('NB preferred over Poisson:', p_od < 0.05)

Overdispersion LR statistic = 56.2895
p-value (one-sided) = 0.000000
NB preferred over Poisson: True

# Marginal Effects

A marginal effect is the expected change in the number of children when an independent variable increases by one unit, ceteris paribus. Compute them the same way as for the logit models.

In [11]:
from marginaleffects import avg_comparisons, comparisons

## Average marginal effects of income

In [12]:
avg_comparisons(po_lm2, variables='income_10k')

shape: (1, 7)
┌──────────┬───────────┬───────┬─────────┬───────┬─────────┬───────┐
│ Estimate ┆ Std.Error ┆ z     ┆ P(>|z|) ┆ S     ┆ 2.5%    ┆ 97.5% │
│ ---      ┆ ---       ┆ ---   ┆ ---     ┆ ---   ┆ ---     ┆ ---   │
│ str      ┆ str       ┆ str   ┆ str     ┆ str   ┆ str     ┆ str   │
╞══════════╪═══════════╪═══════╪═════════╪═══════╪═════════╪═══════╡
│ 0.00124  ┆ 0.0075    ┆ 0.165 ┆ 0.869   ┆ 0.203 ┆ -0.0135 ┆ 0.016 │
└──────────┴───────────┴───────┴─────────┴───────┴─────────┴───────┘
Term: income_10k
Contrast: +1

In [13]:
avg_comparisons(nb_m1, variables='income_10k')

shape: (1, 7)
┌──────────┬───────────┬────────┬─────────┬───────┬────────┬────────┐
│ Estimate ┆ Std.Error ┆ z      ┆ P(>|z|) ┆ S     ┆ 2.5%   ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---    ┆ ---     ┆ ---   ┆ ---    ┆ ---    │
│ str      ┆ str       ┆ str    ┆ str     ┆ str   ┆ str    ┆ str    │
╞══════════╪═══════════╪════════╪═════════╪═══════╪════════╪════════╡
│ 0.00077  ┆ 0.00953   ┆ 0.0808 ┆ 0.936   ┆ 0.096 ┆ -0.018 ┆ 0.0195 │
└──────────┴───────────┴────────┴─────────┴───────┴────────┴────────┘
Term: income_10k
Contrast: +1

## Marginal effect at the mean of income

In [14]:
comparisons(po_lm2, variables='income_10k', newdata='mean')

shape: (1, 7)
┌──────────┬───────────┬───────┬─────────┬───────┬─────────┬────────┐
│ Estimate ┆ Std.Error ┆ z     ┆ P(>|z|) ┆ S     ┆ 2.5%    ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---   ┆ ---     ┆ ---   ┆ ---     ┆ ---    │
│ str      ┆ str       ┆ str   ┆ str     ┆ str   ┆ str     ┆ str    │
╞══════════╪═══════════╪═══════╪═════════╪═══════╪═════════╪════════╡
│ 0.0012   ┆ 0.00727   ┆ 0.165 ┆ 0.869   ┆ 0.203 ┆ -0.0131 ┆ 0.0155 │
└──────────┴───────────┴───────┴─────────┴───────┴─────────┴────────┘
Term: income_10k
Contrast: +1

In [15]:
comparisons(nb_m1, variables='income_10k', newdata='mean')

shape: (1, 7)
┌──────────┬───────────┬────────┬─────────┬───────┬─────────┬────────┐
│ Estimate ┆ Std.Error ┆ z      ┆ P(>|z|) ┆ S     ┆ 2.5%    ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---    ┆ ---     ┆ ---   ┆ ---     ┆ ---    │
│ str      ┆ str       ┆ str    ┆ str     ┆ str   ┆ str     ┆ str    │
╞══════════╪═══════════╪════════╪═════════╪═══════╪═════════╪════════╡
│ 0.000746 ┆ 0.00923   ┆ 0.0808 ┆ 0.936   ┆ 0.096 ┆ -0.0174 ┆ 0.0189 │
└──────────┴───────────┴────────┴─────────┴───────┴─────────┴────────┘
Term: income_10k
Contrast: +1

# Independent Investigation: Education and Number of Children

Investigate the relationship between **no. of children** (`biokids`) and **BA education** (`ba_binary`).

Do the following:

1. Include these independent variables: `ba_binary`, `age`, `income_10k`, `sex_woman`, and `race_bin`.
2. Build OLS, Poisson, and Negative Binomial models.
3. Produce a Stargazer table comparing the three models.
4. Compute marginal effects for each model.
5. Decide which model is best. Justify.
6. Answer: does a person with a BA have more or fewer children, and by how much? For the Poisson and negative binomial models, report a factor of change or a percentage change.

In [22]:
# OLS MODEL

ols_lm3 = smf.ols('biokids ~ ba_binary', data=df).fit()
print(ols_lm3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                biokids   R-squared:                       0.017
Model:                            OLS   Adj. R-squared:                  0.016
Method:                 Least Squares   F-statistic:                     9.794
Date:                Tue, 13 Oct 2026   Prob (F-statistic):            0.00184
Time:                        13:20:01   Log-Likelihood:                -1045.6
No. Observations:                 557   AIC:                             2095.
Df Residuals:                     555   BIC:                             2104.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.7797      0.092     19.294      0.000       1.598       1.961
ba_binary     -0.4209      0.134     -3.129      0.002      -0.685      -0.157
==============================================================================
Omnibus:                      153.936   Durbin-Watson:                   1.835
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              460.580
Skew:                           1.318   Prob(JB):                    9.69e-101
Kurtosis:                       6.592   Cond. No.                         2.55
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [20]:
df["ba_binary"].value_counts()

ba_binary
0    295
1    262
Name: count, dtype: int64

For respondents with a degree, the number of children they have is estimated to decrease by 0.42 on average compared to respondents without a degree. However, at the individual level, it is physically impossible for a person to have 0.42 less children.

In [23]:
# POISSON MODEL

po_lm3 = smf.poisson('biokids ~ ba_binary', data=df).fit()
print(po_lm3.summary())

Optimization terminated successfully.
         Current function value: 1.753595
         Iterations 4
                          Poisson Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:                        Poisson   Df Residuals:                      555
Method:                           MLE   Df Model:                            1
Date:                Tue, 13 Oct 2026   Pseudo R-squ.:                0.007958
Time:                        13:20:16   Log-Likelihood:                -976.75
converged:                       True   LL-Null:                       -984.59
Covariance Type:            nonrobust   LLR p-value:                 7.542e-05
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.5764      0.044     13.208      0.000       0.491       0.662
ba_binary     -0.2698      0.069     -3.930      0.000      -0.404      -0.135
==============================================================================

for participants with a degree, they are estimated to have less children by 0.27 log counts on average, compared to those without a degree.

In [24]:
# NB MODEL

nb_m3 = smf.negativebinomial('biokids ~ ba_binary', data=df).fit()
print(nb_m3.summary())

Optimization terminated successfully.
         Current function value: 1.691216
         Iterations: 7
         Function evaluations: 8
         Gradient evaluations: 8
                     NegativeBinomial Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:               NegativeBinomial   Df Residuals:                      555
Method:                           MLE   Df Model:                            1
Date:                Tue, 13 Oct 2026   Pseudo R-squ.:                0.004841
Time:                        13:24:44   Log-Likelihood:                -942.01
converged:                       True   LL-Null:                       -946.59
Covariance Type:            nonrobust   LLR p-value:                  0.002468
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.5764      0.058      9.890      0.000       0.462       0.691
ba_binary     -0.2698      0.089     -3.039      0.002      -0.444      -0.096
alpha          0.4401      0.078      5.643      0.000       0.287       0.593
==============================================================================

For participants with a degree, they are estimated to have less children by 0.27 log counts on average.

In [25]:
lr_od = 2 * (nb_m3.llf - po_lm3.llf)
p_od  = 0.5 * chi2.sf(lr_od, 1)
print(f'Overdispersion LR statistic = {lr_od:.4f}')
print(f'p-value (one-sided) = {p_od:.6f}')
print('NB preferred over Poisson:', p_od < 0.05)

Overdispersion LR statistic = 69.4907
p-value (one-sided) = 0.000000
NB preferred over Poisson: True

As there is significant overdispersion (p-value < 0.001), the negative binomial model is better than the Poisson model.

In [26]:
# STARGAZER

from stargazer.stargazer import Stargazer

sg2 = Stargazer([ols_lm3, po_lm3, nb_m3])
sg2.title('Number of Children')
sg.custom_columns(['OLS', 'Poisson', 'Neg. Binomial'], [1, 1, 1])

# Ending the cell on the object itself renders the table in the notebook
sg2

In [28]:
avg_comparisons(po_lm3, variables='ba_binary')

shape: (1, 7)
┌──────────┬───────────┬───────┬──────────┬──────┬────────┬────────┐
│ Estimate ┆ Std.Error ┆ z     ┆ P(>|z|)  ┆ S    ┆ 2.5%   ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---   ┆ ---      ┆ ---  ┆ ---    ┆ ---    │
│ str      ┆ str       ┆ str   ┆ str      ┆ str  ┆ str    ┆ str    │
╞══════════╪═══════════╪═══════╪══════════╪══════╪════════╪════════╡
│ -0.421   ┆ 0.106     ┆ -3.97 ┆ 8.01e-05 ┆ 13.6 ┆ -0.629 ┆ -0.213 │
└──────────┴───────────┴───────┴──────────┴──────┴────────┴────────┘
Term: ba_binary
Contrast: 1 - 0

In [30]:
avg_comparisons(nb_m3, variables='ba_binary')

shape: (1, 7)
┌──────────┬───────────┬───────┬─────────┬─────┬────────┬───────┐
│ Estimate ┆ Std.Error ┆ z     ┆ P(>|z|) ┆ S   ┆ 2.5%   ┆ 97.5% │
│ ---      ┆ ---       ┆ ---   ┆ ---     ┆ --- ┆ ---    ┆ ---   │
│ str      ┆ str       ┆ str   ┆ str     ┆ str ┆ str    ┆ str   │
╞══════════╪═══════════╪═══════╪═════════╪═════╪════════╪═══════╡
│ -0.421   ┆ 0.138     ┆ -3.05 ┆ 0.0024  ┆ 8.7 ┆ -0.692 ┆ -0.15 │
└──────────┴───────────┴───────┴─────────┴─────┴────────┴───────┘
Term: ba_binary
Contrast: 1 - 0

In [31]:
b = po_lm3.params['ba_binary']
print(f'Factor of change, exp(b): {np.exp(b):.4f}')
print(f'Percentage change, 100 * [exp(b) - 1]: {100 * (np.exp(b) - 1):.2f}%')

Factor of change, exp(b): 0.7635
Percentage change, 100 * [exp(b) - 1]: -23.65%

Using average marginal effects, all the models estimated that respondents with a degree, on average, will have 0.42 fewer children than those without a degree, suggesting that education level is negatively associated with the number of children. These are significant outcomes (p<0.001). 

Based on percentage change, having a degree is estimated with 23.65% decrease on average in the number of children one has, compared to those without a degree.

The negative binomial model is the most effective model as alpha = 0.44 accounts for overdispersion in the Poisson model.