# HS4002 Week 8

## Practising with Count Models

Research question: **what factors influence the number of children someone has?**

We'll compare three model types for count outcomes:
1. OLS (baseline)
2. Poisson regression
3. Negative Binomial regression

Plus: overdispersion testing and marginal effects.

In [4]:
# !pip install pandas numpy plotnine statsmodels stargazer marginaleffects scipy

import pandas as pd
import numpy as np
from plotnine import *
import warnings
warnings.filterwarnings('ignore')
import statsmodels.formula.api as smf
from scipy.stats import chi2

In [5]:
raw_df = pd.read_csv("gss2022_mini2.csv")

chosen_variables = [
	'id', 'age', 'happy', 'yrlvmus', 'yrartxbt', 'yrmovie', 'yrcreat',
	'income16', 'prestg10', 'degree', 'race', 'sex', 'wrkstat', 'biokids', 'educ'
]
df = raw_df[chosen_variables].dropna().copy()

income_map = {
	1: 500,    2: 2000,   3: 3500,   4: 4500,   5: 5500,   6: 6500,
	7: 7500,   8: 9000,   9: 11250,  10: 13750, 11: 16250, 12: 18750,
	13: 21250, 14: 23750, 15: 27500, 16: 32500, 17: 37500, 18: 45000,
	19: 55000, 20: 67500, 21: 82500, 22: 100000, 23: 120000, 24: 140000,
	25: 160000, 26: 250000
}
df['income_cont']   = df['income16'].map(income_map)
df['income_10k']   = df['income_cont'] / 10000
df['age']       = raw_df.loc[df.index, 'age'] - 18

df['binary_lvmus']  = (df['yrlvmus']  == 1).astype(int)
df['binary_artxbt'] = (df['yrartxbt'] == 1).astype(int)
df['binary_movie']  = (df['yrmovie']  == 1).astype(int)
df['binary_creat']  = (df['yrcreat']  == 1).astype(int)
df['omni'] = df[['binary_lvmus','binary_artxbt','binary_movie','binary_creat']].sum(axis=1)

df['race_bin']   = pd.Categorical(df['race'].astype(str))
df['race_cat']   = df['race'].map({1: 'White', 2: 'Black'}).fillna('Other')
df['ba_binary']  = (df['degree'] >= 3).astype(int)
df['sex_woman']  = pd.Categorical(
    np.where(df['sex'] == 2, 'Woman', 'Not Woman'),
    categories=['Not Woman', 'Woman']
)
df['working']    = np.where(df['wrkstat'] <= 3, 'Working', 'Not Working')
df['happy_bin']  = (df['happy'] <= 2).astype(int)
df['happy_cat']  = np.where(df['happy'] <= 2, 'Happy', 'Not Happy')

# Starting with an OLS model

Regress no. of children (`biokids`) against income in ten thousands (`income_10k`). Note: one unit = $10,000. Name this `ols_lm1`.

In [6]:
ols_lm1 = smf.ols('biokids ~ income_10k', data=df).fit()
print(ols_lm1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                biokids   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                   0.04228
Date:                Tue, 13 Oct 2026   Prob (F-statistic):              0.837
Time:                        11:21:48   Log-Likelihood:                -1050.5
No. Observations:                 557   AIC:                             2105.
Df Residuals:                     555   BIC:                             2114.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.5647      0.107     14.639      0.000       1.355       1.775
income_10k     0.0020      0.010      0.206      0.837      -0.017       0.021
==============================================================================
Omnibus:                      147.242   Durbin-Watson:                   1.830
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              411.395
Skew:                           1.287   Prob(JB):                     4.64e-90
Kurtosis:                       6.332   Cond. No.                         17.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

How would you interpret the coefficient for `income_10k`? What is unusual about using OLS on a count variable?

Interpretation: 0.0020 would tells us the expected change in the number of children a person has when income increases by 10,000 dollars, ceteris pairbus (p>0.1). This is unusual because a count variable is impossible to equals to 0.0020. A count variable could only be integers --> poission model.

# Continuing with a Poisson Model

Use `smf.poisson()` — equivalent to `glm(..., family='poisson')` in R.

In [7]:
po_lm1 = smf.poisson('biokids ~ income_10k', data=df).fit()
print(po_lm1.summary())

Optimization terminated successfully.
         Current function value: 1.767601
         Iterations 3
                          Poisson Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:                        Poisson   Df Residuals:                      555
Method:                           MLE   Df Model:                            1
Date:                Tue, 13 Oct 2026   Pseudo R-squ.:               3.454e-05
Time:                        11:21:52   Log-Likelihood:                -984.55
converged:                       True   LL-Null:                       -984.59
Covariance Type:            nonrobust   LLR p-value:                    0.7942
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4478      0.053      8.410      0.000       0.343       0.552
income_10k     0.0012      0.005      0.261      0.794      -0.008       0.011
==============================================================================

Interpret the coefficient on `income_10k`. Do not read it as you would an OLS coefficient.

Poisson coefficients are **factors of change**: a one-unit change in `income_10k` is expected to change the number of children by a factor of exp(β), ceteris paribus.

You can alternatively read this as a **percentage change**: 100 × [exp(β) − 1]%.

Interpretation: A 10,000 dollars increase in income is expected to change the number of children by a factor of 0.0012, ceteris paribus (p>0.1).

In [8]:
import numpy as np
b = po_lm1.params['income_10k']
print(f'Factor of change, exp(b): {np.exp(b):.4f}')
print(f'Percentage change, 100 * [exp(b) - 1]: {100 * (np.exp(b) - 1):.2f}%')

Factor of change, exp(b): 1.0012
Percentage change, 100 * [exp(b) - 1]: 0.12%

# Adding Age

Add `age` to both models. `age` is centered at 18, so 0 is an 18-year-old. Save as `ols_lm2` and `po_lm2`.

In [9]:
ols_lm2 = smf.ols('biokids ~ income_10k + age', data=df).fit()
po_lm2  = smf.poisson('biokids ~ income_10k + age', data=df).fit()
print(po_lm2.summary())

Optimization terminated successfully.
         Current function value: 1.720780
         Iterations 5
                          Poisson Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:                        Poisson   Df Residuals:                      554
Method:                           MLE   Df Model:                            2
Date:                Tue, 13 Oct 2026   Pseudo R-squ.:                 0.02652
Time:                        11:21:58   Log-Likelihood:                -958.47
converged:                       True   LL-Null:                       -984.59
Covariance Type:            nonrobust   LLR p-value:                 4.563e-12
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0674      0.094     -0.720      0.472      -0.251       0.116
income_10k     0.0008      0.005      0.165      0.869      -0.009       0.010
age            0.0143      0.002      7.151      0.000       0.010       0.018
==============================================================================

Interpretation: One year increase in age is expected to change the number of children by a factor of 0.0143, ceteris paribus (p>0.1).

## Comparing the Poisson Models via Likelihood Ratio Test

In [10]:
lr_stat = 2 * (po_lm2.llf - po_lm1.llf)
df_diff = po_lm2.df_model - po_lm1.df_model
p_val   = chi2.sf(lr_stat, df_diff)
print(f'LR statistic = {lr_stat:.4f}, df = {df_diff:.0f}, p-value = {p_val:.6f}')

LR statistic = 52.1579, df = 1, p-value = 0.000000

Interpretation: We observed that LR statistics = 52.16 and p-value less than 0.01
The null hypothesis is the true value of LR statistic is 0; the alternative is the true value of LR statistic is not 0.
The p-value tells us there is a probability of < 0.001 that we obtain an estimated LR statistics of 52.16 or more extreme if the true value of LR statistics = 0.
As p < 0.001, this seems quite unlikely under null, so we reject H0.

# Building a Negative Binomial Model

Negative binomial relaxes the Poisson assumption that variance = mean (allowing overdispersion).

Equivalent to R's `MASS::glm.nb()`.

Read the coefficients the same way as in a Poisson model: as a factor of change, exp(β), or as a percentage change, 100 × [exp(β) − 1]%.

In [11]:
nb_m1 = smf.negativebinomial('biokids ~ income_10k + age', data=df).fit()
print(nb_m1.summary())

Optimization terminated successfully.
         Current function value: 1.670251
         Iterations: 14
         Function evaluations: 19
         Gradient evaluations: 19
                     NegativeBinomial Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:               NegativeBinomial   Df Residuals:                      554
Method:                           MLE   Df Model:                            2
Date:                Tue, 13 Oct 2026   Pseudo R-squ.:                 0.01718
Time:                        11:22:04   Log-Likelihood:                -930.33
converged:                       True   LL-Null:                       -946.59
Covariance Type:            nonrobust   LLR p-value:                 8.681e-08
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.0832      0.116     -0.718      0.473      -0.310       0.144
income_10k     0.0005      0.006      0.081      0.936      -0.011       0.012
age            0.0148      0.003      5.755      0.000       0.010       0.020
alpha          0.3822      0.073      5.212      0.000       0.239       0.526
==============================================================================

Interpretation: 10,000 dollars increase in increase is expected to change the number of children by a factor of 0.0005, ceteris paribus (p>0.1).

In [12]:
%pip install stargazer

Requirement already satisfied: stargazer in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (0.0.7)
Note: you may need to restart the kernel to use updated packages.

In [13]:
from stargazer.stargazer import Stargazer

sg = Stargazer([ols_lm2, po_lm2, nb_m1])
sg.title('Number of Children')
sg.custom_columns(['OLS', 'Poisson', 'Neg. Binomial'], [1, 1, 1])

# Ending the cell on the object itself renders the table in the notebook
sg

## Test for Overdispersion

Was NB necessary? We test whether the NB's dispersion parameter (alpha) is significantly different from 0. If alpha = 0, the NB reduces to Poisson.

This is equivalent to R's `pscl::odTest()`.

In [14]:
# Overdispersion test: LR comparing NB vs Poisson
# Under H0 (Poisson), the test statistic has a chi-square(1)/2 distribution
# because the null is on the boundary of the parameter space
lr_od = 2 * (nb_m1.llf - po_lm2.llf)
p_od  = 0.5 * chi2.sf(lr_od, 1)
print(f'Overdispersion LR statistic = {lr_od:.4f}')
print(f'p-value (one-sided) = {p_od:.6f}')
print('NB preferred over Poisson:', p_od < 0.05)

Overdispersion LR statistic = 56.2895
p-value (one-sided) = 0.000000
NB preferred over Poisson: True

Interpretation: We estimate an overdispersion LR statistic of 56.29, with a p-value less than 0.001.
The null hypothesis is that the true value of overdispersion LR statistic = 0; the alternative is Overdispersion LR statistic /= 0)
The p-value tells us there is a probability of < 0.001 that we obtain an estimated |r(hat)| of 0.42 or more extreme if the true value of r=0.
As p < 0.001, this seems quite unlikely under null, so we reject H0.

# Marginal Effects

A marginal effect is the expected change in the number of children when an independent variable increases by one unit, ceteris paribus. Compute them the same way as for the logit models.

In [15]:
%pip install marginaleffects

Requirement already satisfied: marginaleffects in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (0.6.1)
Requirement already satisfied: formulaic>=1.0.2 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (1.2.2)
Requirement already satisfied: jax>=0.4.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (0.11.1)
Requirement already satisfied: narwhals>=1.34.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (2.26.0)
Requirement already satisfied: numpy>=2.0.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (2.5.2)
Requirement already satisfied: patsy>=1.0.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (1.0.2)
Requirement already satisfied: polars>=1.26.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (1.44.2)
Requirement already satisfied: pydantic>=2.10.3 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (2.13.5)
Requirement already satisfied: plotnine>=0.14.5 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (0.15.7)
Requirement already satisfied: scipy>=1.14.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (1.18.0)
Requirement already satisfied: pyarrow>=19.0.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (25.0.1)
Requirement already satisfied: interface-meta>=1.2.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from formulaic>=1.0.2->marginaleffects) (2.0.1)
Requirement already satisfied: pandas>=1.3 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from formulaic>=1.0.2->marginaleffects) (3.0.5)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from formulaic>=1.0.2->marginaleffects) (4.16.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from formulaic>=1.0.2->marginaleffects) (2.4.1)
Requirement already satisfied: jaxlib<=0.11.1,>=0.11.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from jax>=0.4.0->marginaleffects) (0.11.1)
Requirement already satisfied: ml_dtypes>=0.5.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from jax>=0.4.0->marginaleffects) (0.6.0)
Requirement already satisfied: opt_einsum in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from jax>=0.4.0->marginaleffects) (3.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from pandas>=1.3->formulaic>=1.0.2->marginaleffects) (2.9.0.post0)
Requirement already satisfied: matplotlib>=3.8.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from plotnine>=0.14.5->marginaleffects) (3.11.1)
Requirement already satisfied: mizani~=0.14.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from plotnine>=0.14.5->marginaleffects) (0.14.4)
Requirement already satisfied: statsmodels>=0.14.6 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from plotnine>=0.14.5->marginaleffects) (0.14.6)
Requirement already satisfied: contourpy>=1.0.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (26.3)
Requirement already satisfied: pillow>=9 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (3.3.2)
Requirement already satisfied: polars-runtime-32==1.44.2 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from polars>=1.26.0->marginaleffects) (1.44.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from pydantic>=2.10.3->marginaleffects) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from pydantic>=2.10.3->marginaleffects) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from pydantic>=2.10.3->marginaleffects) (0.4.4)
Requirement already satisfied: six>=1.5 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas>=1.3->formulaic>=1.0.2->marginaleffects) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
from marginaleffects import avg_comparisons, comparisons

## Average marginal effects of income

In [17]:
print(type(po_lm2))
print(po_lm2.model.__class__)
print(po_lm2.model.data.orig_exog.dtypes)

<class 'statsmodels.discrete.discrete_model.PoissonResultsWrapper'>
<class 'statsmodels.discrete.discrete_model.Poisson'>
Intercept     float64
income_10k    float64
age           float64
dtype: object

In [18]:
import polars as pl
print(pl.__version__)

1.44.2

In [19]:
%pip install -U marginaleffects

Requirement already satisfied: marginaleffects in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (0.6.1)
Requirement already satisfied: formulaic>=1.0.2 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (1.2.2)
Requirement already satisfied: jax>=0.4.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (0.11.1)
Requirement already satisfied: narwhals>=1.34.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (2.26.0)
Requirement already satisfied: numpy>=2.0.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (2.5.2)
Requirement already satisfied: patsy>=1.0.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (1.0.2)
Requirement already satisfied: polars>=1.26.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (1.44.2)
Requirement already satisfied: pydantic>=2.10.3 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (2.13.5)
Requirement already satisfied: plotnine>=0.14.5 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (0.15.7)
Requirement already satisfied: scipy>=1.14.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (1.18.0)
Requirement already satisfied: pyarrow>=19.0.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from marginaleffects) (25.0.1)
Requirement already satisfied: interface-meta>=1.2.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from formulaic>=1.0.2->marginaleffects) (2.0.1)
Requirement already satisfied: pandas>=1.3 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from formulaic>=1.0.2->marginaleffects) (3.0.5)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from formulaic>=1.0.2->marginaleffects) (4.16.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from formulaic>=1.0.2->marginaleffects) (2.4.1)
Requirement already satisfied: jaxlib<=0.11.1,>=0.11.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from jax>=0.4.0->marginaleffects) (0.11.1)
Requirement already satisfied: ml_dtypes>=0.5.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from jax>=0.4.0->marginaleffects) (0.6.0)
Requirement already satisfied: opt_einsum in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from jax>=0.4.0->marginaleffects) (3.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from pandas>=1.3->formulaic>=1.0.2->marginaleffects) (2.9.0.post0)
Requirement already satisfied: matplotlib>=3.8.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from plotnine>=0.14.5->marginaleffects) (3.11.1)
Requirement already satisfied: mizani~=0.14.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from plotnine>=0.14.5->marginaleffects) (0.14.4)
Requirement already satisfied: statsmodels>=0.14.6 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from plotnine>=0.14.5->marginaleffects) (0.14.6)
Requirement already satisfied: contourpy>=1.0.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (26.3)
Requirement already satisfied: pillow>=9 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from matplotlib>=3.8.0->plotnine>=0.14.5->marginaleffects) (3.3.2)
Requirement already satisfied: polars-runtime-32==1.44.2 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from polars>=1.26.0->marginaleffects) (1.44.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from pydantic>=2.10.3->marginaleffects) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from pydantic>=2.10.3->marginaleffects) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from pydantic>=2.10.3->marginaleffects) (0.4.4)
Requirement already satisfied: six>=1.5 in /Users/yangjianru/hs4002_ay26/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas>=1.3->formulaic>=1.0.2->marginaleffects) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
avg_comparisons(po_lm2, variables='income_10k')

shape: (1, 7)
┌──────────┬───────────┬───────┬─────────┬───────┬─────────┬───────┐
│ Estimate ┆ Std.Error ┆ z     ┆ P(>|z|) ┆ S     ┆ 2.5%    ┆ 97.5% │
│ ---      ┆ ---       ┆ ---   ┆ ---     ┆ ---   ┆ ---     ┆ ---   │
│ str      ┆ str       ┆ str   ┆ str     ┆ str   ┆ str     ┆ str   │
╞══════════╪═══════════╪═══════╪═════════╪═══════╪═════════╪═══════╡
│ 0.00124  ┆ 0.0075    ┆ 0.165 ┆ 0.869   ┆ 0.203 ┆ -0.0135 ┆ 0.016 │
└──────────┴───────────┴───────┴─────────┴───────┴─────────┴───────┘
Term: income_10k
Contrast: +1

In [21]:
avg_comparisons(nb_m1, variables='income_10k')

shape: (1, 7)
┌──────────┬───────────┬────────┬─────────┬───────┬────────┬────────┐
│ Estimate ┆ Std.Error ┆ z      ┆ P(>|z|) ┆ S     ┆ 2.5%   ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---    ┆ ---     ┆ ---   ┆ ---    ┆ ---    │
│ str      ┆ str       ┆ str    ┆ str     ┆ str   ┆ str    ┆ str    │
╞══════════╪═══════════╪════════╪═════════╪═══════╪════════╪════════╡
│ 0.00077  ┆ 0.00953   ┆ 0.0808 ┆ 0.936   ┆ 0.096 ┆ -0.018 ┆ 0.0195 │
└──────────┴───────────┴────────┴─────────┴───────┴────────┴────────┘
Term: income_10k
Contrast: +1

## Marginal effect at the mean of income

In [22]:
comparisons(po_lm2, variables='income_10k', newdata='mean')

shape: (1, 7)
┌──────────┬───────────┬───────┬─────────┬───────┬─────────┬────────┐
│ Estimate ┆ Std.Error ┆ z     ┆ P(>|z|) ┆ S     ┆ 2.5%    ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---   ┆ ---     ┆ ---   ┆ ---     ┆ ---    │
│ str      ┆ str       ┆ str   ┆ str     ┆ str   ┆ str     ┆ str    │
╞══════════╪═══════════╪═══════╪═════════╪═══════╪═════════╪════════╡
│ 0.0012   ┆ 0.00727   ┆ 0.165 ┆ 0.869   ┆ 0.203 ┆ -0.0131 ┆ 0.0155 │
└──────────┴───────────┴───────┴─────────┴───────┴─────────┴────────┘
Term: income_10k
Contrast: +1

In [23]:
comparisons(nb_m1, variables='income_10k', newdata='mean')

shape: (1, 7)
┌──────────┬───────────┬────────┬─────────┬───────┬─────────┬────────┐
│ Estimate ┆ Std.Error ┆ z      ┆ P(>|z|) ┆ S     ┆ 2.5%    ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---    ┆ ---     ┆ ---   ┆ ---     ┆ ---    │
│ str      ┆ str       ┆ str    ┆ str     ┆ str   ┆ str     ┆ str    │
╞══════════╪═══════════╪════════╪═════════╪═══════╪═════════╪════════╡
│ 0.000746 ┆ 0.00923   ┆ 0.0808 ┆ 0.936   ┆ 0.096 ┆ -0.0174 ┆ 0.0189 │
└──────────┴───────────┴────────┴─────────┴───────┴─────────┴────────┘
Term: income_10k
Contrast: +1

# Independent Investigation: Education and Number of Children

Investigate the relationship between **no. of children** (`biokids`) and **BA education** (`ba_binary`).

Do the following:

1. Include these independent variables: `ba_binary`, `age`, `income_10k`, `sex_woman`, and `race_bin`.
2. Build OLS, Poisson, and Negative Binomial models.
3. Produce a Stargazer table comparing the three models.
4. Compute marginal effects for each model.
5. Decide which model is best. Justify.
6. Answer: does a person with a BA have more or fewer children, and by how much? For the Poisson and negative binomial models, report a factor of change or a percentage change.

In [ ]:
#OLS model
ols_edu = smf.ols('biokids ~ ba_binary + age + income_10k + sex_woman + race_bin', data=df).fit()
print(ols_edu.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                biokids   R-squared:                       0.118
Model:                            OLS   Adj. R-squared:                  0.109
Method:                 Least Squares   F-statistic:                     12.29
Date:                Tue, 13 Oct 2026   Prob (F-statistic):           5.36e-13
Time:                        11:31:24   Log-Likelihood:                -1015.5
No. Observations:                 557   AIC:                             2045.
Df Residuals:                     550   BIC:                             2075.
Df Model:                           6
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              0.4837      0.190      2.547      0.011       0.111       0.857
sex_woman[T.Woman]     0.4935      0.130      3.798      0.000       0.238       0.749
race_bin[T.2.0]        0.6263      0.201      3.117      0.002       0.232       1.021
race_bin[T.3.0]        0.0643      0.282      0.228      0.820      -0.489       0.618
ba_binary             -0.4814      0.141     -3.410      0.001      -0.759      -0.204
age                    0.0233      0.004      6.202      0.000       0.016       0.031
income_10k             0.0216      0.010      2.165      0.031       0.002       0.041
==============================================================================
Omnibus:                      156.400   Durbin-Watson:                   1.934
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              482.642
Skew:                           1.327   Prob(JB):                    1.57e-105
Kurtosis:                       6.709   Cond. No.                         175.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [ ]:
# Poisson Model
po_edu = smf.poisson('biokids ~ ba_binary + age + income_10k + sex_woman + race_bin', data=df).fit()
print(po_edu.summary())

Optimization terminated successfully.
         Current function value: 1.671346
         Iterations 5
                          Poisson Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:                        Poisson   Df Residuals:                      550
Method:                           MLE   Df Model:                            6
Date:                Tue, 13 Oct 2026   Pseudo R-squ.:                 0.05449
Time:                        11:38:53   Log-Likelihood:                -930.94
converged:                       True   LL-Null:                       -984.59
Covariance Type:            nonrobust   LLR p-value:                 7.505e-21
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             -0.3234      0.112     -2.885      0.004      -0.543      -0.104
sex_woman[T.Woman]     0.3184      0.070      4.564      0.000       0.182       0.455
race_bin[T.2.0]        0.3711      0.094      3.955      0.000       0.187       0.555
race_bin[T.3.0]        0.0390      0.157      0.249      0.803      -0.268       0.346
ba_binary             -0.3114      0.075     -4.136      0.000      -0.459      -0.164
age                    0.0154      0.002      7.507      0.000       0.011       0.019
income_10k             0.0142      0.005      2.749      0.006       0.004       0.024
======================================================================================

In [ ]:
# Negative binomial model
nb_edu = smf.negativebinomial('biokids ~ ba_binary + age + income_10k + sex_woman + race_bin', data=df).fit()
print(nb_edu.summary())

Optimization terminated successfully.
         Current function value: 1.637030
         Iterations: 28
         Function evaluations: 34
         Gradient evaluations: 34
                     NegativeBinomial Regression Results
==============================================================================
Dep. Variable:                biokids   No. Observations:                  557
Model:               NegativeBinomial   Df Residuals:                      550
Method:                           MLE   Df Model:                            6
Date:                Tue, 13 Oct 2026   Pseudo R-squ.:                 0.03673
Time:                        11:39:57   Log-Likelihood:                -911.83
converged:                       True   LL-Null:                       -946.59
Covariance Type:            nonrobust   LLR p-value:                 5.111e-13
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             -0.3463      0.134     -2.591      0.010      -0.608      -0.084
sex_woman[T.Woman]     0.3242      0.085      3.808      0.000       0.157       0.491
race_bin[T.2.0]        0.3756      0.119      3.143      0.002       0.141       0.610
race_bin[T.3.0]        0.0414      0.189      0.219      0.827      -0.330       0.413
ba_binary             -0.3301      0.093     -3.551      0.000      -0.512      -0.148
age                    0.0160      0.003      6.348      0.000       0.011       0.021
income_10k             0.0149      0.006      2.322      0.020       0.002       0.028
alpha                  0.2962      0.066      4.486      0.000       0.167       0.426
======================================================================================

In [ ]:
#Comparing the three model
from stargazer.stargazer import Stargazer

sg_edu = Stargazer([ols_edu, po_edu, nb_edu])
sg_edu.title('Education and Number of Children')
sg_edu.custom_columns(['OLS', 'Poisson', 'Neg. Binomial'], [1, 1, 1])

sg_edu

In [28]:
# Marginal effects
avg_comparisons(ols_edu, variables='ba_binary')

shape: (1, 7)
┌──────────┬───────────┬───────┬──────────┬──────┬────────┬────────┐
│ Estimate ┆ Std.Error ┆ z     ┆ P(>|z|)  ┆ S    ┆ 2.5%   ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---   ┆ ---      ┆ ---  ┆ ---    ┆ ---    │
│ str      ┆ str       ┆ str   ┆ str      ┆ str  ┆ str    ┆ str    │
╞══════════╪═══════════╪═══════╪══════════╪══════╪════════╪════════╡
│ -0.481   ┆ 0.141     ┆ -3.41 ┆ 0.000698 ┆ 10.5 ┆ -0.759 ┆ -0.204 │
└──────────┴───────────┴───────┴──────────┴──────┴────────┴────────┘
Term: ba_binary
Contrast: 1 - 0

In [29]:
avg_comparisons(po_edu, variables='ba_binary')

shape: (1, 7)
┌──────────┬───────────┬───────┬──────────┬──────┬────────┬────────┐
│ Estimate ┆ Std.Error ┆ z     ┆ P(>|z|)  ┆ S    ┆ 2.5%   ┆ 97.5%  │
│ ---      ┆ ---       ┆ ---   ┆ ---      ┆ ---  ┆ ---    ┆ ---    │
│ str      ┆ str       ┆ str   ┆ str      ┆ str  ┆ str    ┆ str    │
╞══════════╪═══════════╪═══════╪══════════╪══════╪════════╪════════╡
│ -0.486   ┆ 0.117     ┆ -4.17 ┆ 3.55e-05 ┆ 14.8 ┆ -0.715 ┆ -0.257 │
└──────────┴───────────┴───────┴──────────┴──────┴────────┴────────┘
Term: ba_binary
Contrast: 1 - 0

In [30]:
avg_comparisons(nb_edu, variables='ba_binary')

shape: (1, 7)
┌──────────┬───────────┬───────┬──────────┬──────┬────────┬───────┐
│ Estimate ┆ Std.Error ┆ z     ┆ P(>|z|)  ┆ S    ┆ 2.5%   ┆ 97.5% │
│ ---      ┆ ---       ┆ ---   ┆ ---      ┆ ---  ┆ ---    ┆ ---   │
│ str      ┆ str       ┆ str   ┆ str      ┆ str  ┆ str    ┆ str   │
╞══════════╪═══════════╪═══════╪══════════╪══════╪════════╪═══════╡
│ -0.515   ┆ 0.145     ┆ -3.55 ┆ 0.000419 ┆ 11.2 ┆ -0.801 ┆ -0.23 │
└──────────┴───────────┴───────┴──────────┴──────┴────────┴───────┘
Term: ba_binary
Contrast: 1 - 0

Which model is the best?
Answer: We observed that alpha = 0.296 (p<0.01). Thus we reject null hypothesis, there is an overdispersion. Therefore, negative binomial model is the best model over the three model, as number of children is a count variable with a significant overdispersion.

Answer: People with a BA tend to have fewer children than people without BA. 

For ols model: We observe that, on average, being people with a BA degree is associated with a 0.481 decrease in the number of children a person has, compared to the people without a BA degree (p<0.01), ceteris paribus.

For poission model: We observe that, on average, being people with a BA degree is associated with a 26.7% decrease in the number of children a person has, compared to the people without a BA degree (p<0.01), ceteris paribus.

For negative binomial model: We observe that, on average, being people with a BA degree is associated with a 28.1% decrease in the number of children a person has, compared to the people without a BA degree (p<0.01). ceteris paribus.